<p>testo di prova</p>

<form>
<table>
    <tr>
        <td>servizio</td>
        <td>header</td>
        <td>footer</td>
    </tr>
    <tr>
        <td>pixel <input type="text"></td>
        <td>
            <select>
                <option value="header">Header</option>
                <option value="footer">Footer</option>
            </select>
        </td>
    </tr>
    <tr>
        <td>analytics <input type="text"> </td>
        <td>
            <select>
                <option value="header">Header</option>
                <option value="footer">Footer</option>
            </select>
        </td>
    </tr>
    <tr>
        <td>
            <input type="submit">
        </td
    ></tr>
</table>

</form>